"""Initial schema

Revision ID: 0b654549a32a
Revises: 
Create Date: 2026-01-19 17:15:42.742840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b654549a32a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'access_token',
               existing_type=sa.VARCHAR(),
               type_=backend.models.EncryptedString(),
               existing_nullable=False)
    op.alter_column('tokens', 'refresh_token',
               existing_type=sa.VARCHAR(),
               type_=backend.models.EncryptedString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'refresh_token',
               existing_type=backend.models.EncryptedString(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('tokens', 'access_token',
               existing_type=backend.models.EncryptedString(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
